[formatting]
line_length = 79

[ai]
rules = ""
mode = "manual"

[ai.models]
custom_models = []
displayed_models = []

[experimental]

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[runtime]
reactive_tests = true
on_cell_change = "lazy"
auto_instantiate = false
default_auto_download = []
default_sql_output = "auto"
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
auto_reload = "off"
output_max_bytes = 8000000

[display]
code_editor_font_size = 14
theme = "light"
default_width = "medium"
default_table_page_size = 10
cell_output = "above"
default_table_max_columns = 50
reference_highlighting = false
dataframes = "rich"

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true

[completion]
copilot = false
activate_on_typing = true

[language_servers.pylsp]
enable_flake8 = false
enable_pydocstyle = false
enabled = true
enable_pylint = false
enable_mypy = true
enable_ruff = true
enable_pyflakes = false

[package_management]
manager = "pip"
