[[session]]
name = "All Config Files"
path = "~/.config"

[[session]]
name = "Configure Tmux"
path = "~/.config/tmux"

[[session]]
name = "Configure Neovim"
path = "~/.config/nvim-lazy"

[[session]]
name = "Configure Zsh"
path = "~/.config/zsh"

[[session]]
name = "Configure Sesh"
path = "~/.config/sesh"

[[session]]
name = "Configure Aerospace"
path = "~/.config/aerospace"

[[session]]
name = "Configure Ghostty"
path = "~/.config/ghostty"
